// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAdXnABkaswnB4lFuUTnFAD83pM0el9s',
    appId: '1:392800324338:web:798abe469a0ae5298a1e6b',
    messagingSenderId: '392800324338',
    projectId: 'appeasydonate',
    authDomain: 'appeasydonate.firebaseapp.com',
    databaseURL: 'https://appeasydonate-default-rtdb.firebaseio.com',
    storageBucket: 'appeasydonate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0S1DrMPmyVj_wPBSfngmRLoHsxseKFs',
    appId: '1:392800324338:android:b3a7a48cdeed1d5d8a1e6b',
    messagingSenderId: '392800324338',
    projectId: 'appeasydonate',
    databaseURL: 'https://appeasydonate-default-rtdb.firebaseio.com',
    storageBucket: 'appeasydonate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa-wLd2B1oGQqxBoSazoKjBSkrycCUWHo',
    appId: '1:392800324338:ios:cf6895b1f38663f88a1e6b',
    messagingSenderId: '392800324338',
    projectId: 'appeasydonate',
    databaseURL: 'https://appeasydonate-default-rtdb.firebaseio.com',
    storageBucket: 'appeasydonate.appspot.com',
    iosClientId: '392800324338-mik3kblo7ch10iva45so68tgsr02gkje.apps.googleusercontent.com',
    iosBundleId: 'com.example.appEasyDonate',
  );
}
